version: "3"

services:
  apache2:
    container_name: apache-php
    image: eriktonon/php:5.6
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ${DOCUMENT_ROOT-./html}:/var/www/html
      - ${PHP_INI-./.docker/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./.docker/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    networks: 
      - lamp-stack
  mysql:
    container_name: mysql
    image: eriktonon/mysql:5.7.27
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    env_file: 
      - .env
    command:  mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    networks: 
      - lamp-stack
networks:
  lamp-stack: